# Vagrant configuration
Vagrant.configure(2) do |config|
  # Configures the base vagrant box found in https://atlas.hashicorp.com/
  config.vm.box = "boxcutter/ubuntu1504-desktop"

  # Configure the VirtualBox provider for the VM
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
	
	# Provide a name to the VM
	vb.name = "ICSE-2012-BabelRef"
  end
 
  # Use shell script to install specific software required to
  # run the tool
  config.vm.provision "shell", inline: <<-SHELL
	# Install Java 8
	sudo apt-get -y install software-properties-common
	sudo add-apt-repository ppa:webupd8team/java
	sudo apt-get update
	sudo apt-get upgrade
	sudo echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
	sudo apt-get install -y oracle-java8-installer	
    
	# Copy Eclipse 4.2
	sudo mkdir /home/vagrant/software   
	
	wget -O /home/vagrant/software/eclipse.tar.gz.00 https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/Eclipse%204.2/eclipse.tar.gz.00
	wget -O /home/vagrant/software/eclipse.tar.gz.01 https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/Eclipse%204.2/eclipse.tar.gz.01
	wget -O /home/vagrant/software/eclipse.tar.gz.02 https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/Eclipse%204.2/eclipse.tar.gz.02
	wget -O /home/vagrant/software/eclipse.tar.gz.03 https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/Eclipse%204.2/eclipse.tar.gz.03
	wget -O /home/vagrant/software/eclipse.tar.gz.04 https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/Eclipse%204.2/eclipse.tar.gz.04
	wget -O /home/vagrant/software/eclipse.tar.gz.05 https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/Eclipse%204.2/eclipse.tar.gz.05
	wget -O /home/vagrant/software/eclipse.tar.gz.06 https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/Eclipse%204.2/eclipse.tar.gz.06
    cd /home/vagrant/software/ && sudo cat eclipse.tar.gz.* | tar -xvj -C /
	
	# Delete the compressed files
	sudo rm -f "/home/vagrant/software/eclipse.tar.gz.00"
	sudo rm -f "/home/vagrant/software/eclipse.tar.gz.01"
	sudo rm -f "/home/vagrant/software/eclipse.tar.gz.02"
	sudo rm -f "/home/vagrant/software/eclipse.tar.gz.03"
	sudo rm -f "/home/vagrant/software/eclipse.tar.gz.04"
	sudo rm -f "/home/vagrant/software/eclipse.tar.gz.05"
	sudo rm -f "/home/vagrant/software/eclipse.tar.gz.06"
	
	sudo chown -R vagrant /home/vagrant/software/
	
	# Copy the BabelRef workspace for Eclipse
	wget -O /home/vagrant/workspace.tar.gz https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/workspace.tar.gz
	cd /home/vagrant/ && sudo tar -zxvf workspace.tar.gz
	sudo rm -f "/home/vagrant/workspace.tar.gz"
	sudo chown -R vagrant /home/vagrant/workspace/
	
	#sudo chown -R vagrant /home/vagrant/software/eclipse/configuration/org.eclipse.osgi
	sudo chmod -R a+rwx "/home/vagrant/software/"
	ln -s /home/vagrant/software/eclipse/eclipse "/home/vagrant/Desktop/Eclipse 4.2"
	
	# Copy BabelRef binaries from GitHub
	sudo mkdir "/home/vagrant/Desktop/BabelRef Plugin Jars"
	sudo wget -O "/home/vagrant/Desktop/BabelRef Plugin Jars/Data_Model_1.0.0.0.jar" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/Binaries/Data_Model_1.0.0.0.jar
	sudo wget -O "/home/vagrant/Desktop/BabelRef Plugin Jars/Html_Partial_Parser_1.0.0.0.jar" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/Binaries/Html_Partial_Parser_1.0.0.0.jar
	sudo wget -O "/home/vagrant/Desktop/BabelRef Plugin Jars/Util_1.0.0.0.jar" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/Binaries/Util_1.0.0.0.jar
	sudo wget -O "/home/vagrant/Desktop/BabelRef Plugin Jars/Web_Entities_1.0.0.0.jar" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/Binaries/Web_Entities_1.0.0.0.jar
	sudo wget -O "/home/vagrant/Desktop/BabelRef Plugin Jars/edu.iastate.hungnv.babelref_1.0.0.0.jar" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/Binaries/edu.iastate.hungnv.babelref_1.0.0.0.jar
	sudo chown -R vagrant "/home/vagrant/Desktop/BabelRef Plugin Jars"	
	
	# Add Eclipse as startup application
	sudo mkdir "/home/vagrant/.config/autostart"
	wget -O "/home/vagrant/.config/autostart/eclipse.desktop" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/eclipse.desktop

	# Copy readme, installation, licenses, acknowledgments, how-to video links to vm desktop
	wget -O "/home/vagrant/Desktop/Installation.txt" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/Installation.txt
	wget -O "/home/vagrant/Desktop/Readme.txt" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/Readme.txt
	wget -O "/home/vagrant/Desktop/BabelRef - How to use on this VM.desktop" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/BabelRef%20-%20How%20to%20use%20on%20this%20VM.desktop
	wget -O "/home/vagrant/Desktop/BabelRef - Video Demo from Author.desktop" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/BabelRef%20-%20Video%20Demo%20from%20Author.desktop
	wget -O "/home/vagrant/Desktop/Licenses.txt" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/Licenses.txt
	wget -O "/home/vagrant/Desktop/Acknowledgement.txt" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/Acknowledgement.txt
	sudo chown -R vagrant "/home/vagrant/Desktop"
	sudo chmod -R a+rwx "/home/vagrant/Desktop"
	
	# Install Adobe Flash Player plugin to view youtube videos
	sudo apt-get install flashplugin-installer 
	
	
	# Remove unnecessary launcher applications
	sudo rm -f "/usr/share/applications/ubuntu-amazon-default.desktop"
	sudo rm -f "/usr/share/applications/libreoffice-calc.desktop"
	sudo rm -f "/usr/share/applications/libreoffice-writer.desktop"
	sudo rm -f "/usr/share/applications/libreoffice-impress.desktop"
	sudo rm -f "/usr/share/applications/ubuntu-software-center.desktop"
	sudo rm -f "/usr/share/applications/unity-control-center.desktop"

	# Disable screen lock
	sudo mkdir "/home/vagrant/software/scripts"
	wget -O "/home/vagrant/software/scripts/screenlock.sh" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/screenlock.sh
	wget -O "/home/vagrant/.config/autostart/screenlock.desktop" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/screenlock.desktop
	sudo chmod -R a+rwx "/home/vagrant/software/scripts/"
	
	# Reboot the VM
	sudo reboot
	
  SHELL
end
