# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant configuration
Vagrant.configure(2) do |config|
  # Configures the base vagrant box found in https://atlas.hashicorp.com/
  config.vm.box = "boxcutter/ubuntu1504-desktop"

  # Configure the VirtualBox provider for the VM
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
	
	# Provide a name to the VM
	vb.name = "ICSE-2012-BabelRef"
  end
 
  # Use shell script to install specific software required to
  # run the tool
  config.vm.provision "shell", inline: <<-SHELL
	# Install Java 8
	sudo apt-get -y install software-properties-common
	sudo add-apt-repository ppa:webupd8team/java
	sudo apt-get update
	sudo apt-get upgrade
	sudo echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
	sudo apt-get install -y oracle-java8-installer	
    
	# Install the VirtualBox guest additions for better performance and usability
    #sudo apt-get install -y virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11
	
	# Copy Eclipse 4.2
	sudo mkdir /home/vagrant/software   
    #wget -O /home/vagrant/software/eclipse-jee-juno-SR2-linux-gtk-x86_64.tar.gz http://eclipse.mirror.rafal.ca/technology/epp/downloads/release/juno/SR2/eclipse-jee-juno-SR2-linux-gtk-x86_64.tar.gz
    #cd /home/vagrant/software/ && sudo tar -zxvf eclipse-jee-juno-SR2-linux-gtk-x86_64.tar.gz
	
    cd /home/vagrant/software/ && sudo cat /home/vagrant/software/eclipse.tar.gz.* | tar -xvj
	
	sudo rm -f "/home/vagrant/software/eclipse-jee-juno-SR2-linux-gtk-x86_64.tar.gz"
	sudo chown -R vagrant /home/vagrant/software/
	sudo chown -R vagrant /home/vagrant/software/eclipse/configuration
	sudo chmod -R a+rwx "/home/vagrant/software/eclipse/configuration"
	
	#sudo chown -R vagrant /home/vagrant/software/eclipse/configuration/org.eclipse.osgi
	sudo chmod -R a+rwx "/home/vagrant/software/"
	ln -s /home/vagrant/software/eclipse/eclipse "/home/vagrant/Desktop/Eclipse 4.2"
	
	# Copy BabelRef binaries from GitHub
	sudo mkdir "/home/vagrant/Desktop/BabelRef Plugin Jars"
	sudo wget -O "/home/vagrant/Desktop/BabelRef Plugin Jars/Data_Model_1.0.0.0.jar" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/Binaries/Data_Model_1.0.0.0.jar
	sudo wget -O "/home/vagrant/Desktop/BabelRef Plugin Jars/Html_Partial_Parser_1.0.0.0.jar" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/Binaries/Html_Partial_Parser_1.0.0.0.jar
	sudo wget -O "/home/vagrant/Desktop/BabelRef Plugin Jars/Util_1.0.0.0.jar" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/Binaries/Util_1.0.0.0.jar
	sudo wget -O "/home/vagrant/Desktop/BabelRef Plugin Jars/Web_Entities_1.0.0.0.jar" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/Binaries/Web_Entities_1.0.0.0.jar
	sudo wget -O "/home/vagrant/Desktop/BabelRef Plugin Jars/edu.iastate.hungnv.babelref_1.0.0.0.jar" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/Binaries/edu.iastate.hungnv.babelref_1.0.0.0.jar
	sudo chown -R vagrant "/home/vagrant/Desktop/BabelRef Plugin Jars"
	
	# Copy BabelRef binaries to the Eclipse Dropins folder
	sudo cp -a "/home/vagrant/Desktop/BabelRef Plugin Jars/." /home/vagrant/software/eclipse/dropins/
		
	# Install eclipse
	#sudo apt-get install eclipse-platform
	
	# Copy sample PHP project from GitHub
	#sudo mkdir /home/vagrant/workspace
	sudo wget -O "/home/vagrant/Desktop/BabelRef PHP Project.zip" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/BabelRef%20PHP%20Project.zip
	sudo unzip "/home/vagrant/Desktop/BabelRef PHP Project.zip" -d /home/vagrant/Desktop/
	#sudo chown -R vagrant "/home/vagrant/workspace"
	#sudo chmod -R a+rwx "/home/vagrant/workspace"
	sudo rm -f "/home/vagrant/Desktop/BabelRef PHP Project.zip"
	
	# Copy readme, installation, licenses, acknowledgments, how-to video links to vm desktop
	wget -O "/home/vagrant/Desktop/Readme.txt" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/Readme.txt
	wget -O "/home/vagrant/Desktop/Installation.txt" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/Installation.txt
	wget -O "/home/vagrant/Desktop/Licenses.txt" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/Licenses.txt
	wget -O "/home/vagrant/Desktop/Acknowledgement.txt" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/Acknowledgement.txt
	wget -O "/home/vagrant/Desktop/BabelRef - How to use on this VM.desktop" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/BabelRef%20-%20How%20to%20use%20on%20this%20VM.desktop
	wget -O "/home/vagrant/Desktop/BabelRef - Video Demo from Author.desktop" https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-BabelRef/raw/master/build-vm/vm-contents/BabelRef%20-%20Video%20Demo%20from%20Author.desktop
	sudo chown -R vagrant "/home/vagrant/Desktop"
	sudo chmod -R a+rwx "/home/vagrant/Desktop"
	
	# Install Adobe Flash Player plugin to view youtube videos
	sudo apt-get install flashplugin-installer 
	
	# Launch eclipse
	#sudo /home/vagrant/software/eclipse/eclipse -data /home/vagrant/workspace

	#sudo chown -R vagrant /home/vagrant/software/
	#sudo chown -R vagrant /home/vagrant/software/eclipse/configuration
	#sudo chmod -R a+rwx "/home/vagrant/software/eclipse/configuration"

	#sudo /home/vagrant/software/eclipse/eclipse -data /home/vagrant/workspace
	
  SHELL
end
